name: Deploy to Production

on:
  workflow_dispatch:          # вручную из UI
  push:
    branches:
      - master
    # Игнорируем все файлы и папки, имена которых начинаются с "."
    paths-ignore:
      - '.*'       # скрытые файлы в корне: .gitignore, .env и т.п.
      - '.*/**'    # любые скрытые папки
      - '**/.*'    # скрытые файлы в любых подпапках: config/.secret, dir/.env и т.п.

jobs:
  rsync-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rsync and SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync openssh-client

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          RSYNC="${{ vars.RSYNC }}"
          while IFS= read -r RSYNC_TO; do
            REMOTE_HOST=$(echo "$RSYNC_TO" | sed -En 's#^([^@]+)@([^:]+)(:([0-9]+))?:(.*)$#\2#p')
            REMOTE_PORT=$(echo "$RSYNC_TO" | sed -En 's#^([^@]+)@([^:]+)(:([0-9]+))?:(.*)$#\4#p')
            if [ -z $REMOTE_PORT ]; then
              REMOTE_PORT="22"
            fi
            ssh-keyscan -H $REMOTE_HOST -p $REMOTE_PORT >> ~/.ssh/known_hosts
          done <<< "$RSYNC"

      - name: Rsync to remote server (excluding Git)
        run: |
          RSYNC="${{ vars.RSYNC }}"
          while IFS= read -r RSYNC_TO; do
            REMOTE_USER=$(echo "$RSYNC_TO" | sed -En 's#^([^@]+)@([^:]+)(:([0-9]+))?:(.*)$#\1#p')
            REMOTE_HOST=$(echo "$RSYNC_TO" | sed -En 's#^([^@]+)@([^:]+)(:([0-9]+))?:(.*)$#\2#p')
            REMOTE_PORT=$(echo "$RSYNC_TO" | sed -En 's#^([^@]+)@([^:]+)(:([0-9]+))?:(.*)$#\4#p')
            if [ -z $REMOTE_PORT ]; then
              REMOTE_PORT="22"
            fi
            REMOTE_PATH=$(echo "$RSYNC_TO" | sed -En 's#^([^@]+)@([^:]+)(:([0-9]+))?:(.*)$#\5#p')
            
            rsync -avz --delete -e "ssh -p ${REMOTE_PORT}" \
              --exclude="/.**" \
              ./ \
              "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"
          done <<< "$RSYNC"
